MDBoxLayout:
    orientation:'vertical'

    MDBottomNavigation:

        MDBottomNavigationItem:
            name: 'screen 1'
            text: 'Tracker'
            icon: 'eye-circle'

            MDToolbar:
                title: 'Tracker'
                pos_hint: {"top": 1}

            MDRaisedButton:
                text: 'Keylogger'
                pos_hint: {'center_x': 0.5, 'center_y': 0.8}
                on_release: app.logger()


        MDBottomNavigationItem:
            name: 'screen 2'
            text: 'Encryptor'
            icon: 'shield-lock'

            MDToolbar:
                title: 'Encryptor'
                pos_hint: {"top": 1}
                
            MDFillRoundFlatIconButton:
                text: 'Select text/image file'
                icon: 'folder'
                pos_hint: {'center_x': .3, 'center_y': .7}
                on_release: app.file_manager_open()

            MDFillRoundFlatIconButton:
                text: 'Encrypt'
                icon: 'lock'
                pos_hint: {'center_x': .3, 'center_y': .6}
                on_release: app.to_encrypt()

            MDFillRoundFlatIconButton:
                text: 'Decrypt'
                icon: 'lock-open-variant'
                pos_hint: {'center_x': .3, 'center_y': .5}
                on_release: app.to_encrypt()

        MDBottomNavigationItem:
            name: 'screen 3'
            text: 'Applock'
            icon: 'lock-pattern'

            MDToolbar:
                title: 'Applock'
                pos_hint: {"top": 1}

            MDLabel:
                text: 'Applock'
                halign: 'center'